//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistracijaParcelaClient.RegistracijaParcelaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parcela", Namespace="http://schemas.datacontract.org/2004/07/RegistracijaParcela")]
    [System.SerializableAttribute()]
    public partial class Parcela : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeVlasnikaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Tuple<decimal, decimal>[] KoordinateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImeVlasnika {
            get {
                return this.ImeVlasnikaField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeVlasnikaField, value) != true)) {
                    this.ImeVlasnikaField = value;
                    this.RaisePropertyChanged("ImeVlasnika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Tuple<decimal, decimal>[] Koordinate {
            get {
                return this.KoordinateField;
            }
            set {
                if ((object.ReferenceEquals(this.KoordinateField, value) != true)) {
                    this.KoordinateField = value;
                    this.RaisePropertyChanged("Koordinate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistracijaParcelaServiceReference.IRegistracijaParcelaService")]
    public interface IRegistracijaParcelaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaParcelaService/EchoTest", ReplyAction="http://tempuri.org/IRegistracijaParcelaService/EchoTestResponse")]
        string EchoTest(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaParcelaService/EchoTest", ReplyAction="http://tempuri.org/IRegistracijaParcelaService/EchoTestResponse")]
        System.Threading.Tasks.Task<string> EchoTestAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaParcelaService/RegistrujParcelu", ReplyAction="http://tempuri.org/IRegistracijaParcelaService/RegistrujParceluResponse")]
        void RegistrujParcelu(RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela parcela, string imeVlasnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaParcelaService/RegistrujParcelu", ReplyAction="http://tempuri.org/IRegistracijaParcelaService/RegistrujParceluResponse")]
        System.Threading.Tasks.Task RegistrujParceluAsync(RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela parcela, string imeVlasnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaParcelaService/VratiParceleSaPovrsinom", ReplyAction="http://tempuri.org/IRegistracijaParcelaService/VratiParceleSaPovrsinomResponse")]
        System.Tuple<RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela, decimal>[] VratiParceleSaPovrsinom(string imeVlasnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaParcelaService/VratiParceleSaPovrsinom", ReplyAction="http://tempuri.org/IRegistracijaParcelaService/VratiParceleSaPovrsinomResponse")]
        System.Threading.Tasks.Task<System.Tuple<RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela, decimal>[]> VratiParceleSaPovrsinomAsync(string imeVlasnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaParcelaService/VratiVeceParcele", ReplyAction="http://tempuri.org/IRegistracijaParcelaService/VratiVeceParceleResponse")]
        RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela[] VratiVeceParcele(decimal povrsinaUArima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaParcelaService/VratiVeceParcele", ReplyAction="http://tempuri.org/IRegistracijaParcelaService/VratiVeceParceleResponse")]
        System.Threading.Tasks.Task<RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela[]> VratiVeceParceleAsync(decimal povrsinaUArima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaParcelaService/VratiSveParcele", ReplyAction="http://tempuri.org/IRegistracijaParcelaService/VratiSveParceleResponse")]
        RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela[] VratiSveParcele();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaParcelaService/VratiSveParcele", ReplyAction="http://tempuri.org/IRegistracijaParcelaService/VratiSveParceleResponse")]
        System.Threading.Tasks.Task<RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela[]> VratiSveParceleAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistracijaParcelaServiceChannel : RegistracijaParcelaClient.RegistracijaParcelaServiceReference.IRegistracijaParcelaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistracijaParcelaServiceClient : System.ServiceModel.ClientBase<RegistracijaParcelaClient.RegistracijaParcelaServiceReference.IRegistracijaParcelaService>, RegistracijaParcelaClient.RegistracijaParcelaServiceReference.IRegistracijaParcelaService {
        
        public RegistracijaParcelaServiceClient() {
        }
        
        public RegistracijaParcelaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistracijaParcelaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaParcelaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaParcelaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EchoTest(string message) {
            return base.Channel.EchoTest(message);
        }
        
        public System.Threading.Tasks.Task<string> EchoTestAsync(string message) {
            return base.Channel.EchoTestAsync(message);
        }
        
        public void RegistrujParcelu(RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela parcela, string imeVlasnika) {
            base.Channel.RegistrujParcelu(parcela, imeVlasnika);
        }
        
        public System.Threading.Tasks.Task RegistrujParceluAsync(RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela parcela, string imeVlasnika) {
            return base.Channel.RegistrujParceluAsync(parcela, imeVlasnika);
        }
        
        public System.Tuple<RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela, decimal>[] VratiParceleSaPovrsinom(string imeVlasnika) {
            return base.Channel.VratiParceleSaPovrsinom(imeVlasnika);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela, decimal>[]> VratiParceleSaPovrsinomAsync(string imeVlasnika) {
            return base.Channel.VratiParceleSaPovrsinomAsync(imeVlasnika);
        }
        
        public RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela[] VratiVeceParcele(decimal povrsinaUArima) {
            return base.Channel.VratiVeceParcele(povrsinaUArima);
        }
        
        public System.Threading.Tasks.Task<RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela[]> VratiVeceParceleAsync(decimal povrsinaUArima) {
            return base.Channel.VratiVeceParceleAsync(povrsinaUArima);
        }
        
        public RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela[] VratiSveParcele() {
            return base.Channel.VratiSveParcele();
        }
        
        public System.Threading.Tasks.Task<RegistracijaParcelaClient.RegistracijaParcelaServiceReference.Parcela[]> VratiSveParceleAsync() {
            return base.Channel.VratiSveParceleAsync();
        }
    }
}
