//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZakupSkladistaClient.ZakupSkladistaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vlasnik", Namespace="http://schemas.datacontract.org/2004/07/ZakupSkladista")]
    [System.SerializableAttribute()]
    public partial class Vlasnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JmbgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jmbg {
            get {
                return this.JmbgField;
            }
            set {
                if ((object.ReferenceEquals(this.JmbgField, value) != true)) {
                    this.JmbgField = value;
                    this.RaisePropertyChanged("Jmbg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Skladiste", Namespace="http://schemas.datacontract.org/2004/07/ZakupSkladista")]
    [System.SerializableAttribute()]
    public partial class Skladiste : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zakup", Namespace="http://schemas.datacontract.org/2004/07/ZakupSkladista")]
    [System.SerializableAttribute()]
    public partial class Zakup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdSkladistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JmbgVlasnikaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime KrajZakupaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PocetakZakupaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSkladista {
            get {
                return this.IdSkladistaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSkladistaField, value) != true)) {
                    this.IdSkladistaField = value;
                    this.RaisePropertyChanged("IdSkladista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JmbgVlasnika {
            get {
                return this.JmbgVlasnikaField;
            }
            set {
                if ((object.ReferenceEquals(this.JmbgVlasnikaField, value) != true)) {
                    this.JmbgVlasnikaField = value;
                    this.RaisePropertyChanged("JmbgVlasnika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime KrajZakupa {
            get {
                return this.KrajZakupaField;
            }
            set {
                if ((this.KrajZakupaField.Equals(value) != true)) {
                    this.KrajZakupaField = value;
                    this.RaisePropertyChanged("KrajZakupa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PocetakZakupa {
            get {
                return this.PocetakZakupaField;
            }
            set {
                if ((this.PocetakZakupaField.Equals(value) != true)) {
                    this.PocetakZakupaField = value;
                    this.RaisePropertyChanged("PocetakZakupa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZakupSkladistaServiceReference.IZakupSkladistaService")]
    public interface IZakupSkladistaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladistaService/ZakupiSkladiste", ReplyAction="http://tempuri.org/IZakupSkladistaService/ZakupiSkladisteResponse")]
        ZakupSkladistaClient.ZakupSkladistaServiceReference.Zakup ZakupiSkladiste(ZakupSkladistaClient.ZakupSkladistaServiceReference.Vlasnik vlasnik, ZakupSkladistaClient.ZakupSkladistaServiceReference.Skladiste skladiste, System.DateTime pocetakZakupa, System.DateTime krajZakupa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladistaService/ZakupiSkladiste", ReplyAction="http://tempuri.org/IZakupSkladistaService/ZakupiSkladisteResponse")]
        System.Threading.Tasks.Task<ZakupSkladistaClient.ZakupSkladistaServiceReference.Zakup> ZakupiSkladisteAsync(ZakupSkladistaClient.ZakupSkladistaServiceReference.Vlasnik vlasnik, ZakupSkladistaClient.ZakupSkladistaServiceReference.Skladiste skladiste, System.DateTime pocetakZakupa, System.DateTime krajZakupa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladistaService/VratiAktivnaSkladista", ReplyAction="http://tempuri.org/IZakupSkladistaService/VratiAktivnaSkladistaResponse")]
        ZakupSkladistaClient.ZakupSkladistaServiceReference.Skladiste[] VratiAktivnaSkladista(string jmbgVlasnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladistaService/VratiAktivnaSkladista", ReplyAction="http://tempuri.org/IZakupSkladistaService/VratiAktivnaSkladistaResponse")]
        System.Threading.Tasks.Task<ZakupSkladistaClient.ZakupSkladistaServiceReference.Skladiste[]> VratiAktivnaSkladistaAsync(string jmbgVlasnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladistaService/VratiVlasnikeAktivnihSkladista", ReplyAction="http://tempuri.org/IZakupSkladistaService/VratiVlasnikeAktivnihSkladistaResponse")]
        ZakupSkladistaClient.ZakupSkladistaServiceReference.Vlasnik[] VratiVlasnikeAktivnihSkladista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladistaService/VratiVlasnikeAktivnihSkladista", ReplyAction="http://tempuri.org/IZakupSkladistaService/VratiVlasnikeAktivnihSkladistaResponse")]
        System.Threading.Tasks.Task<ZakupSkladistaClient.ZakupSkladistaServiceReference.Vlasnik[]> VratiVlasnikeAktivnihSkladistaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladistaService/VratiSkladistaSaIstorijomZakupa", ReplyAction="http://tempuri.org/IZakupSkladistaService/VratiSkladistaSaIstorijomZakupaResponse" +
            "")]
        System.Collections.Generic.Dictionary<ZakupSkladistaClient.ZakupSkladistaServiceReference.Skladiste, ZakupSkladistaClient.ZakupSkladistaServiceReference.Zakup[]> VratiSkladistaSaIstorijomZakupa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakupSkladistaService/VratiSkladistaSaIstorijomZakupa", ReplyAction="http://tempuri.org/IZakupSkladistaService/VratiSkladistaSaIstorijomZakupaResponse" +
            "")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<ZakupSkladistaClient.ZakupSkladistaServiceReference.Skladiste, ZakupSkladistaClient.ZakupSkladistaServiceReference.Zakup[]>> VratiSkladistaSaIstorijomZakupaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZakupSkladistaServiceChannel : ZakupSkladistaClient.ZakupSkladistaServiceReference.IZakupSkladistaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZakupSkladistaServiceClient : System.ServiceModel.ClientBase<ZakupSkladistaClient.ZakupSkladistaServiceReference.IZakupSkladistaService>, ZakupSkladistaClient.ZakupSkladistaServiceReference.IZakupSkladistaService {
        
        public ZakupSkladistaServiceClient() {
        }
        
        public ZakupSkladistaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZakupSkladistaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZakupSkladistaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZakupSkladistaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ZakupSkladistaClient.ZakupSkladistaServiceReference.Zakup ZakupiSkladiste(ZakupSkladistaClient.ZakupSkladistaServiceReference.Vlasnik vlasnik, ZakupSkladistaClient.ZakupSkladistaServiceReference.Skladiste skladiste, System.DateTime pocetakZakupa, System.DateTime krajZakupa) {
            return base.Channel.ZakupiSkladiste(vlasnik, skladiste, pocetakZakupa, krajZakupa);
        }
        
        public System.Threading.Tasks.Task<ZakupSkladistaClient.ZakupSkladistaServiceReference.Zakup> ZakupiSkladisteAsync(ZakupSkladistaClient.ZakupSkladistaServiceReference.Vlasnik vlasnik, ZakupSkladistaClient.ZakupSkladistaServiceReference.Skladiste skladiste, System.DateTime pocetakZakupa, System.DateTime krajZakupa) {
            return base.Channel.ZakupiSkladisteAsync(vlasnik, skladiste, pocetakZakupa, krajZakupa);
        }
        
        public ZakupSkladistaClient.ZakupSkladistaServiceReference.Skladiste[] VratiAktivnaSkladista(string jmbgVlasnika) {
            return base.Channel.VratiAktivnaSkladista(jmbgVlasnika);
        }
        
        public System.Threading.Tasks.Task<ZakupSkladistaClient.ZakupSkladistaServiceReference.Skladiste[]> VratiAktivnaSkladistaAsync(string jmbgVlasnika) {
            return base.Channel.VratiAktivnaSkladistaAsync(jmbgVlasnika);
        }
        
        public ZakupSkladistaClient.ZakupSkladistaServiceReference.Vlasnik[] VratiVlasnikeAktivnihSkladista() {
            return base.Channel.VratiVlasnikeAktivnihSkladista();
        }
        
        public System.Threading.Tasks.Task<ZakupSkladistaClient.ZakupSkladistaServiceReference.Vlasnik[]> VratiVlasnikeAktivnihSkladistaAsync() {
            return base.Channel.VratiVlasnikeAktivnihSkladistaAsync();
        }
        
        public System.Collections.Generic.Dictionary<ZakupSkladistaClient.ZakupSkladistaServiceReference.Skladiste, ZakupSkladistaClient.ZakupSkladistaServiceReference.Zakup[]> VratiSkladistaSaIstorijomZakupa() {
            return base.Channel.VratiSkladistaSaIstorijomZakupa();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<ZakupSkladistaClient.ZakupSkladistaServiceReference.Skladiste, ZakupSkladistaClient.ZakupSkladistaServiceReference.Zakup[]>> VratiSkladistaSaIstorijomZakupaAsync() {
            return base.Channel.VratiSkladistaSaIstorijomZakupaAsync();
        }
    }
}
