//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistracijaVozilaClient.RegistracijaVozilaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vlasnik", Namespace="http://schemas.datacontract.org/2004/07/RegistracijaVozila")]
    [System.SerializableAttribute()]
    public partial class Vlasnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JmbgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jmbg {
            get {
                return this.JmbgField;
            }
            set {
                if ((object.ReferenceEquals(this.JmbgField, value) != true)) {
                    this.JmbgField = value;
                    this.RaisePropertyChanged("Jmbg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vozilo", Namespace="http://schemas.datacontract.org/2004/07/RegistracijaVozila")]
    [System.SerializableAttribute()]
    public partial class Vozilo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BojaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boja {
            get {
                return this.BojaField;
            }
            set {
                if ((object.ReferenceEquals(this.BojaField, value) != true)) {
                    this.BojaField = value;
                    this.RaisePropertyChanged("Boja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marka {
            get {
                return this.MarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaField, value) != true)) {
                    this.MarkaField = value;
                    this.RaisePropertyChanged("Marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Registracija", Namespace="http://schemas.datacontract.org/2004/07/RegistracijaVozila")]
    [System.SerializableAttribute()]
    public partial class Registracija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdVozilaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JmbgVlasnikaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime KrajRegistracijeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PocetakRegistracijeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdVozila {
            get {
                return this.IdVozilaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdVozilaField, value) != true)) {
                    this.IdVozilaField = value;
                    this.RaisePropertyChanged("IdVozila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JmbgVlasnika {
            get {
                return this.JmbgVlasnikaField;
            }
            set {
                if ((object.ReferenceEquals(this.JmbgVlasnikaField, value) != true)) {
                    this.JmbgVlasnikaField = value;
                    this.RaisePropertyChanged("JmbgVlasnika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime KrajRegistracije {
            get {
                return this.KrajRegistracijeField;
            }
            set {
                if ((this.KrajRegistracijeField.Equals(value) != true)) {
                    this.KrajRegistracijeField = value;
                    this.RaisePropertyChanged("KrajRegistracije");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PocetakRegistracije {
            get {
                return this.PocetakRegistracijeField;
            }
            set {
                if ((this.PocetakRegistracijeField.Equals(value) != true)) {
                    this.PocetakRegistracijeField = value;
                    this.RaisePropertyChanged("PocetakRegistracije");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistracijaVozilaServiceReference.IRegistracijaVozilaService")]
    public interface IRegistracijaVozilaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozilaService/RegistrujVozilo", ReplyAction="http://tempuri.org/IRegistracijaVozilaService/RegistrujVoziloResponse")]
        RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Registracija RegistrujVozilo(RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vlasnik vlasnik, RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo vozilo, System.DateTime krajRegistracije);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozilaService/RegistrujVozilo", ReplyAction="http://tempuri.org/IRegistracijaVozilaService/RegistrujVoziloResponse")]
        System.Threading.Tasks.Task<RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Registracija> RegistrujVoziloAsync(RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vlasnik vlasnik, RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo vozilo, System.DateTime krajRegistracije);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozilaService/VratiVozila", ReplyAction="http://tempuri.org/IRegistracijaVozilaService/VratiVozilaResponse")]
        RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo[] VratiVozila(string jmbgVlasnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozilaService/VratiVozila", ReplyAction="http://tempuri.org/IRegistracijaVozilaService/VratiVozilaResponse")]
        System.Threading.Tasks.Task<RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo[]> VratiVozilaAsync(string jmbgVlasnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozilaService/VratiIstorijuRegistracija", ReplyAction="http://tempuri.org/IRegistracijaVozilaService/VratiIstorijuRegistracijaResponse")]
        RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Registracija[] VratiIstorijuRegistracija(RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo vozilo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozilaService/VratiIstorijuRegistracija", ReplyAction="http://tempuri.org/IRegistracijaVozilaService/VratiIstorijuRegistracijaResponse")]
        System.Threading.Tasks.Task<RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Registracija[]> VratiIstorijuRegistracijaAsync(RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo vozilo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozilaService/VratiVozilaSaRegistracijama", ReplyAction="http://tempuri.org/IRegistracijaVozilaService/VratiVozilaSaRegistracijamaResponse" +
            "")]
        System.Collections.Generic.Dictionary<RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo, RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Registracija[]> VratiVozilaSaRegistracijama();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozilaService/VratiVozilaSaRegistracijama", ReplyAction="http://tempuri.org/IRegistracijaVozilaService/VratiVozilaSaRegistracijamaResponse" +
            "")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo, RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Registracija[]>> VratiVozilaSaRegistracijamaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistracijaVozilaServiceChannel : RegistracijaVozilaClient.RegistracijaVozilaServiceReference.IRegistracijaVozilaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistracijaVozilaServiceClient : System.ServiceModel.ClientBase<RegistracijaVozilaClient.RegistracijaVozilaServiceReference.IRegistracijaVozilaService>, RegistracijaVozilaClient.RegistracijaVozilaServiceReference.IRegistracijaVozilaService {
        
        public RegistracijaVozilaServiceClient() {
        }
        
        public RegistracijaVozilaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistracijaVozilaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaVozilaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaVozilaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Registracija RegistrujVozilo(RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vlasnik vlasnik, RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo vozilo, System.DateTime krajRegistracije) {
            return base.Channel.RegistrujVozilo(vlasnik, vozilo, krajRegistracije);
        }
        
        public System.Threading.Tasks.Task<RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Registracija> RegistrujVoziloAsync(RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vlasnik vlasnik, RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo vozilo, System.DateTime krajRegistracije) {
            return base.Channel.RegistrujVoziloAsync(vlasnik, vozilo, krajRegistracije);
        }
        
        public RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo[] VratiVozila(string jmbgVlasnika) {
            return base.Channel.VratiVozila(jmbgVlasnika);
        }
        
        public System.Threading.Tasks.Task<RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo[]> VratiVozilaAsync(string jmbgVlasnika) {
            return base.Channel.VratiVozilaAsync(jmbgVlasnika);
        }
        
        public RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Registracija[] VratiIstorijuRegistracija(RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo vozilo) {
            return base.Channel.VratiIstorijuRegistracija(vozilo);
        }
        
        public System.Threading.Tasks.Task<RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Registracija[]> VratiIstorijuRegistracijaAsync(RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo vozilo) {
            return base.Channel.VratiIstorijuRegistracijaAsync(vozilo);
        }
        
        public System.Collections.Generic.Dictionary<RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo, RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Registracija[]> VratiVozilaSaRegistracijama() {
            return base.Channel.VratiVozilaSaRegistracijama();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Vozilo, RegistracijaVozilaClient.RegistracijaVozilaServiceReference.Registracija[]>> VratiVozilaSaRegistracijamaAsync() {
            return base.Channel.VratiVozilaSaRegistracijamaAsync();
        }
    }
}
